GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFjb2IiLCJpYXQiOjE2OTA2NzM5MTIsImV4cCI6MTY5MDY3MzkyN30.IVT5yaQ4cZNSMSF8RrH0Dp1JnnmFGp0X7UX0gh1Ba40
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFjb2IiLCJpYXQiOjE2OTA2NzM4NzR9.A5V_vlzNoJjWDLwh_HE8sKLpdp_Z6GvFhjakm4B1VYY"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFjb2IiLCJpYXQiOjE2OTA2NzM4NzR9.A5V_vlzNoJjWDLwh_HE8sKLpdp_Z6GvFhjakm4B1VYY"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jacob"
}